### ISSUE TITLE
Isomorphism tests for node/browser equivalence

### ISSUE THREAD

**Issue by plfx** [serverless/fdk#51]
The FDK should work equivalently in back-end and front-end applications. The test suite currently runs within the node runtime, but should also cover headless Chrome usage to ensure isomorphic operation.

**Comment by nikgraf** [comment]
We most probably can use this to test it: https://github.com/GoogleChrome/puppeteer

Ideally we test the raw import as well as the dist build done with rollup

**Comment by nikgraf** [comment]
related PR https://github.com/serverless/fdk/pull/68
