### ISSUE TITLE
Unsubscribe for http event not possible if subscriptionId contains "special characters"

### ISSUE THREAD

**Issue by pmuens** [serverless/fdk#71]
I want to unsubscribe an http event with the subscriptionId `http-GET-%2Fhello`.

Unfortunately I get the following error message back:

```
Error: Failed to unsubscribe the subscription http-GET-%2Fhello and couldn't parse error body.
```

Special characters like `%2F` are not problem for the Event Gateway (according to @mthenw). My assumption is that the `fetch` call translates `%2F` into `/` so that the requests [here](https://github.com/serverless/fdk/blob/c25bd68bdaf9c4620492351afaf728dd8d4f4d8a/lib/unsubscribe.js#L10) is translated to `/v1/subscriptions/http-GET-/hello` which erros out because the path is not valid on the event gateways side.

**Comment by pmuens** [comment]
Closing this here since `fetch` seems to take the URL as is and it looks like it's an Event Gateway issue --> https://github.com/serverless/event-gateway/issues/333

**Comment by nikgraf** [comment]
👍
